VIEW_SUPPORT_TICKETS_QRY = """select ticket_id as "ticket id",user_id as "user id",subject,message,status,TO_CHAR(created_at,'DD Mon YYYY, HH:MI AM') as "created at",TO_CHAR(updated_at,'DD Mon YYYY, HH:MI AM') as "updated at",updated_by as "updated by" from supporttickets;"""
VIEW_SUPPORT_RESPONSES_QRY = """select response_id as "response id",ticket_id as "ticket id", message,TO_CHAR(created_at,'DD Mon YYYY, HH:MI AM') as "created at",TO_CHAR(updated_at,'DD Mon YYYY, HH:MI AM') as "updated at",updated_by as "updated by" from supportresponses;"""
UPDATE_ST_STATUS_QRY = "update supporttickets set status=%s,updated_at=current_timestamp,updated_by=%s where ticket_id=%s;"
GET_STS_BY_TID_QRY = "select * from supporttickets where ticket_id=%s;"
GET_SR_BY_RID_QRY = "select * from supportresponses where response_id=%s;"
UPDATE_SR_MESSAGE_QRY = "update supportresponses set message=%s,updated_at=current_timestamp,updated_by=%s where response_id=%s;"
INSERT_SR_QRY = "INSERT INTO SUPPORTRESPONSES (message,ticket_id) values (%s,%s);"
INSERT_ST_QRY = "insert into supporttickets (subject,message,user_id,status) values (%s,%s,%s,'open');" 
GET_ST_STATUS_BY_TID_QRY = "select status from supporttickets where ticket_id=%s"