DISPLAY_DSICOUNT_CODES_QRY = """select discount_id as id,code as "coupan",description,discount_percent as "discount percent",status,CONCAT(max_usage,' times') "maximum usage limit",CONCAT(number_of_times_used,' times') "times used",TO_CHAR(valid_from,'DD-MM-YYYY') "valid from",TO_CHAR(valid_to,'DD-MM-YYYY') "valid to",TO_CHAR(created_at,'DD Mon YYYY, HH:MI AM') AS "created at",TO_CHAR(updated_at, 'DD Mon YYYY, HH:MI AM') AS "updated at",updated_by as "updated by" from discounts order by discount_id;"""
GET_DISCOUNTS_BY_DID_QRY = "select * from discounts where discount_id=%s;"
GET_DISCOUNTS_BY_DCODE_QRY = "select * from discounts where code=%s;"
UPDATE_DCODE_QRY = "UPDATE Discounts set code=%s,updated_by=%s,updated_at=current_timestamp where discount_id=%s;"
UPDATE_DCODE_DESCRIPTION_QRY = "UPDATE Discounts set description=%s,updated_by=%s,updated_at=current_timestamp where discount_id=%s;"
UPDATE_DCODE_PERCENTAGE_QRY = "UPDATE Discounts set discount_percentage=%s,updated_by=%s,updated_at=current_timestamp where discount_id=%s;"
GET_DCODE_VALIDTO_QRY = "select valid_to from Discounts where discount_id=%s;"
GET_DCODE_VALIDFROM_QRY = "select valid_from from Discounts where discount_id=%s;"
UPDATE_DCODE_VALID_FROM_QRY = "update Discounts set valid_from=%s,updated_by=%s,updated_at=current_timestamp where discount_id=%s;"
UPDATE_DCODE_VALID_TO_QRY = "update Discounts set valid_to=%s,updated_by=%s,updated_at=current_timestamp where discount_id=%s;"
UPDATE_DCODE_STATUS_QRY = "update Discounts set status=%s,updated_at=current_timestamp,updated_by=%s where discount_id=%s;"
GET_DCODE_STATUS_BY_DID_QRY = "select status from Discounts where discount_id=%s;"
GET_DCODE_STATUS_BY_DCODE_QRY = "select status from Discounts where code=%s;"
UPDATE_DCODE_MAXUSAGE_QRY = "UPDATE Discounts set max_usage=%s,updated_by=%s,updated_at=current_timestamp where discount_id=%s;"
DELETE_DCODE_QRY = "delete from discounts where discount_id=%s;"
GET_VALIDATE_DCODE_QRY = "SELECT * FROM discounts WHERE code = %s AND NOW() BETWEEN valid_from AND valid_to;"
GET_DCODE_MAXUSAGE_VALIDATE_QRY = "select * from discounts where code=%s and max_usage>0;"
ADD_NEW_DCODE_QRY = "INSERT INTO Discounts (code,description,discount_percent,valid_from,valid_to,status,max_usage) values (%s,%s,%s,%s,%s,%s,%s);"