GET_PRODUCTS_BY_PID_QRY = "select * from Products where product_id = %s;"
GET_PRODUCTS_BY_PNAME_QRY = "select * from Products where name=%s;"
UPDATE_PRODUCT_NAME__QRY = "update products set name=%s,updated_at=current_timestamp,updated_by=%s where product_id=%s;"
UPDATE_PRODUCT_DESCRIPTION_QRY = "update products set description=%s,updated_at=current_timestamp,updated_by=%s where product_id=%s;"
UPDATE_PRODUCT_STOCK_QRY = "update Products set stock=%s,updated_at=current_timestamp,updated_by=%s,base_quantity=%s where product_id=%s;"
PRODUCT_CATEGORY_CEHCKER_QRY = "select * from categories where category_id=%s;"
ADD_NEW_PRODUCT_QRY = "INSERT INTO Products (name,description,price,stock,base_quantity,category_id) values (%s,%s,%s,%s,%s,%s);"
UPDATE_PRODUCT_CATEGORYID_QRY = "UPDATE Products set category_id=%s,updated_by=%s,updated_at=current_timestamp where product_id=%s;"
GET_PPRICE_PID_QRY = "select price from products where product_id=%s;"
UPDATE_PPRICE_QRY = "update products set price=%s,updated_at=current_timestamp,updated_by=%s where product_id=%s;"
GET_CART_UID_QRY = "select * from cart where user_id=%s;"
CREATE_CART_UID_QRY = "insert into cart (user_id) values (%s);"
GET_PSTOCK_BY_PID_QRY = "select stock from products where product_id=%s;"
GET_PBQ_PPRICE_PID_QRY = "select base_quantity,price from products where product_id=%s;"
GET_CARTID_BY_UID_QRY = "select cart_id from cart where user_id=%s;"
INSERT_ITEMS_INTO_CARTITEMS_QRY = "insert into cartitems (product_id,cart_id,quantity,base_quantity,price_at_addition) values (%s,%s,%s,%s,%s);"
GET_CARTITEMS_BY_PID_CARTID_QRY = "select * from cartitems where cart_id=%s and product_id=%s ;"
DELETE_CARTITEM_BY_PID_CARTID_QRY = "delete from cartitems where cart_id=%s and product_id=%s;"  
GET_WID_BY_UID_QRY = "select wishlist_id from wishlist where user_id=%s;"
GET_WITEMS_BY_PID_WID_QRY = "select * from wishlistitems where product_id=%s and wishlist_id=%s;"
DELETE_WITEMS_BY_PID_WID_QRY = "delete from wishlistitems where wishlist_id=%s and product_id=%s;"
GET_WLIST_BY_UID_QRY = "select * from wishlist where user_id=%s;"
CREATE_WISHLIST_BY_UID_QRY = "insert into wishlist (user_id) values (%s);"
INSERT_ITEMS_INTO_WISHLIST_BY_PID_WID_QRY = "insert into wishlistitems (product_id,wishlist_id) values (%s,%s);"
INSERT_INTO_ORDER_GET_OID_QRY = """ INSERT INTO orders (user_id, status, total, order_address, order_city, order_pincode, order_country, order_district) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING order_id;"""
MOVE_ITEMS_FROM_CART_TO_ORDERITEMS_QRY = """ INSERT INTO orderitems (order_id, product_id, quantity, base_quantity, price) SELECT %s, product_id, quantity, base_quantity, price_at_addition FROM cartitems WHERE cart_id = %s;"""
DELETE_ITEMS_FROM_CART_QRY = """DELETE FROM cartitems WHERE cart_id = %s;"""
DELETE_PRODUCT_BY_PID_QRY = "DELETE FROM Products WHERE product_id=%s;"
GET_CATEGORIES_BY_CID_QRY = "select * from categories where category_id=%s;"
GET_DP_BY_DCODE_QRY = "select discount_percent from discounts where code=%s;"
UPDATE_DCODE_USAGE_QRY = "update discounts set number_of_times_used=number_of_times_used+1 where code=%s;"