DISPLAY_USERS_QRY = """SELECT user_id as id, username, gender,email, role, TO_CHAR(bdate, 'DD-MM-YYYY') AS birthdate, TO_CHAR(created_at, 'DD Mon YYYY, HH:MI AM') AS "created at",TO_CHAR(updated_at, 'DD Mon YYYY, HH:MI AM') AS "updated at", updated_by as "updated by"FROM Users order by user_id;""" 
GET_USER_BY_UID_QRY = "select * from users where user_id=%s;"
UPDATE_USERNAME_BY_UID_QRY = "UPDATE USERS SET USERNAME=%s,updated_by=%s,updated_at=current_timestamp where user_id=%s;"
UPDATE_USEREMAIL_BY_UID_QRY = "UPDATE USERS SET email=%s,updated_by=%s,updated_at=current_timestamp where user_id=%s;"
UPDATE_USER_GENDER_BY_UID_QRY = "UPDATE USERS SET GENDER=%s,updated_by=%s,updated_at=current_timestamp where user_id=%s;"
GET_GENDER_BY_UID_QRY = "select gender from users where user_id=%s;"
UPDATE_USER_BDATE_BY_UID_QRY = "UPDATE USERS SET bdate=TO_DATE(%s,'DD-MM-YYYY'),updated_by=%s,updated_at=current_timestamp where user_id=%s;"
GET_UID_BY_UNAME_QRY = "select user_id from users where username=%s;"
DELETE_USER_BY_UID_QRY = "DELETE FROM USERS WHERE user_id=%s;"
INSERT_NEW_USER_QRY = "INSERT INTO USERS (username,password,role,email,gender,bdate) values (%s,%s,%s,%s,%s,%s);"
DIPLAY_USER_REGISTRATION_REQUESTS_QRY = "select * from userregistrationrequests;"
GET_USER_FROM_URR_BY_REQUEST_ID_QRY = "select * from userregistrationrequests where request_id=%s;"
UPDATE_UREGISTRATION_REQUEST_QRY = "UPDATE UserRegistrationRequests SET status = %s WHERE request_id = %s;"
MOVE_USER_FRROM_RR_TO_USERS_QRY = "INSERT INTO Users (username, password, email, role, bdate, gender) SELECT username, password, email, role,bdate, gender FROM UserRegistrationRequests WHERE request_id = %s;"